services:
  traefik:
    container_name: 'traefik'
    image: traefik:v3.2
    networks:
      - traefik
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/etc/traefik/:${TRAEFIK_BASE_PATH}'
      - '/etc/traefik/acme:${TRAEFIK_BASE_PATH}/acme'
    command: 
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
    ports:
      - 80:80
      - 443:443
      - 8183:8183
      - 8080:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entrypoints=http
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.rule=Host(`traefik.home`)
  jellyfin:
    container_name: 'jellyfin'
    image: linuxserver/jellyfin:2021.12.16
    networks:
      - traefik
    volumes:
      - '${MEDIA_BASE_PATH}/movies:/movies'
      - '${MEDIA_BASE_PATH}/series:/series'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.home`)'
      - 'traefik.http.routers.jellyfin.entrypoints=http'
      - 'traefik.http.routers.jellyfin.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.jellyfin.tls=${TLS}'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'
    #command: '--gpu all --runtime nvidia'
  nextcloud:
    container_name: 'nextcloud'
    image: nextcloud:30
    user: ${CLOUD_SYS_USER}
    ports:
      - 8888:80
    depends_on:
      - nextcloud_db
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${CLOUD_ADMIN_PASSWORD}
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${CLOUD_DB_PASSWORD}
      - POSTGRES_HOST=nextcloud_db
      - PHP_UPLOAD_LIMIT=20G
    volumes:
      - '${CLOUD_BASE_PATH}/html:/var/www/html'
      - '${CLOUD_BASE_PATH}/custom_apps:/var/www/html/custom_apps'
      - '${CLOUD_BASE_PATH}/config:/var/www/html/config'
      - '${CLOUD_BASE_PATH}/data:/var/www/html/data'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.cloud.rule=Host(`cloud.home`)'
      - 'traefik.http.routers.cloud.entrypoints=http'
      - 'traefik.http.routers.cloud.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.cloud.tls=${TLS}'
      - 'traefik.http.services.cloud.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.nextcloud-redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav'
      - 'traefik.http.middlewares.nextcloud-redirect.redirectregex.replacement=https://$${1}/remote.php/dav/'
      - 'traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=15552000'
      - 'traefik.http.middlewares.nextcloud-headers.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.nextcloud-headers.headers.stsPreload=true'
      - 'traefik.http.middlewares.nextcloud-headers.headers.stsIncludeSubdomains=true'
    networks:
      - traefik
      - nextcloud

  nextcloud_db:
    container_name: nextcloud_db
    image: postgres:12.20-alpine
    user: ${CLOUD_SYS_USER}
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${CLOUD_DB_PASSWORD}
    volumes:
      - '${CLOUD_BASE_PATH}/db:/var/lib/postgresql/data'
    networks:
      - nextcloud
 
networks:
  traefik:
  media:
  nextcloud: